// This is a placeholder for a base64-encoded image that would be generated by an AI model like Imagen.
// The prompt for such an image might be:
// "A futuristic and abstract digital art of a financial stock chart with glowing neural network patterns overlaid.
// Minimalist, clean, with blue and green highlights on a dark background. Cyberpunk aesthetic."
//
// To avoid embedding a very large string in the codebase, we are using a simple 1x1 transparent pixel as a placeholder.
// In a real application, this might be fetched from a server or generated on-demand.

export const welcomeImageBase64 = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNkYAAAAAYAAjCB0C8AAAAASUVORK5CYII=";
